// Generated by https://quicktype.io

export interface Ctx {
  params: Params;
  locales: string;
  locale: string;
  defaultLocale: string;
}

export interface Params {
  id: string;
  name: string;
}
